# Generated by Django 4.2.6 on 2023-10-25 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_advertisement_datecreation'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='advertisement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='board.advertisement'),
            preserve_default=False,
        ),
    ]
