# Generated by Django 4.2.6 on 2023-10-31 13:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0002_response_status_alter_advertisement_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('author', 'advertisement')},
        ),
    ]
