# Generated by Django 4.2.6 on 2023-10-31 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_response_author'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set(),
        ),
    ]
